# Generated by Django 3.1.1 on 2020-11-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_contentreadytodownload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentreadytodownload',
            name='number_of_times_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
