# Generated by Django 3.1.1 on 2021-01-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210125_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('user_upload_image_file_path', models.CharField(default='not found', max_length=200)),
                ('downloaded', models.BooleanField(default=False)),
                ('sku', models.CharField(default='323f88cb-f394-431c-a9e1-c55a3d067ba2', max_length=254)),
            ],
        ),
    ]
