# Generated by Django 3.1.1 on 2021-01-01 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20210101_2113'),
        ('profiles', '0003_auto_20201111_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentreadytodownload',
            name='product_file_path',
        ),
        migrations.AddField(
            model_name='contentreadytodownload',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
