# Generated by Django 3.1.1 on 2021-01-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='1db806d4-28a3-4d8f-bba0-2ec07951ea17', max_length=254),
        ),
    ]
