# Generated by Django 3.1.1 on 2021-01-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210128_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='0e1f0505-e0d6-46da-abc8-16bc334d637f', max_length=254),
        ),
    ]
