# Generated by Django 3.1.1 on 2021-01-01 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210101_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentreadytodownload',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
