# Generated by Django 3.1.1 on 2021-01-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210129_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='18364ec0-efc7-4e45-bce1-2fe5b9a109cf', max_length=254),
        ),
    ]
