# Generated by Django 3.1.1 on 2020-10-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20201030_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number_of_ratings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
