# Generated by Django 3.1.1 on 2020-11-30 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_image_upload_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default=uuid.UUID('450fe38b-dd2f-400d-92b6-cba5d7e24805'), max_length=254),
        ),
    ]
