# Generated by Django 3.1.1 on 2020-11-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20201130_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='d2858b51-7bc7-4ef5-a633-fe7da76b47b5', max_length=254),
        ),
    ]
