# Generated by Django 3.1.1 on 2020-12-07 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201111_2201'),
        ('products', '0026_auto_20201204_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_upload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_photo', to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='75ccbaaf-13c4-4398-bd98-92ebaba39050', max_length=254),
        ),
    ]
