# Generated by Django 3.1.1 on 2020-12-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20201209_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='c480b1d0-86fe-4fa3-ba7f-c5b84b102839', max_length=254),
        ),
    ]
