# Generated by Django 3.1.1 on 2020-12-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20201212_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='bde4377b-07f9-478c-9deb-aef2b3933b95', max_length=254),
        ),
    ]
