# Generated by Django 3.1.1 on 2020-10-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_taken',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='location',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
