# Generated by Django 3.1.1 on 2020-10-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201022_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
