# Generated by Django 3.1.1 on 2020-10-24 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_blog'),
        ('blog', '0005_blog_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='sku',
        ),
        migrations.AddField(
            model_name='blog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
