# Generated by Django 3.1.1 on 2020-10-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201024_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='product',
            new_name='sku',
        ),
    ]
