# Generated by Django 3.1.1 on 2020-10-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201024_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='sku',
            new_name='product',
        ),
    ]
