# Generated by Django 3.1.1 on 2020-10-24 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_blog'),
        ('blog', '0010_remove_blog_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_mobile_from_url', to='products.product'),
        ),
    ]
