# Generated by Django 3.1.1 on 2021-01-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blog_image_desktop_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='new_blog', max_length=254),
        ),
    ]
