# Generated by Django 3.1.1 on 2020-12-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='lineitem_total',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='digital_download',
            field=models.BooleanField(default=False),
        ),
    ]
