# Generated by Django 3.1.1 on 2020-12-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_remove_orderlineitem_order_linked_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='order_linked_products',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
