# Generated by Django 3.1.1 on 2020-12-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_orderlineitem_order_linked_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='order_linked_products',
        ),
    ]
