# Generated by Django 3.1.1 on 2020-12-09 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20201209_2251'),
        ('checkout', '0011_linked_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='linked_product',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_product', to='products.product'),
        ),
    ]
