# Generated by Django 3.1.1 on 2020-10-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20201007_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='customer_username',
            field=models.CharField(default='Anonymous', max_length=254),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_content',
            field=models.TextField(default="There hasn't been a review added yet."),
        ),
    ]
