# Generated by Django 3.1.1 on 2020-10-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20201012_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_content',
            field=models.TextField(default=''),
        ),
    ]
