# Generated by Django 3.1.1 on 2020-12-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20201030_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='customer_username',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.CharField(default='User not found', max_length=254),
        ),
    ]
