# Generated by Django 3.1.1 on 2021-01-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210109_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='f26801c9-72c6-4580-bb03-3a67921a875a', max_length=254),
        ),
    ]
