# Generated by Django 3.1.1 on 2020-10-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201006_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='blog',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
