# Generated by Django 3.1.1 on 2021-01-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210109_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='f336f981-69a4-4b02-b33a-0e2cd1e72c93', max_length=254),
        ),
        migrations.AlterField(
            model_name='special',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
