# Generated by Django 3.1.1 on 2021-01-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210109_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='330f7754-8b05-4fa6-8904-91a68e827c10', max_length=254),
        ),
        migrations.AlterField(
            model_name='special',
            name='name',
            field=models.CharField(blank=True, default='none', max_length=254),
        ),
    ]
