# Generated by Django 3.1.1 on 2020-10-06 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201006_2139'),
        ('products', '0004_product_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blog'),
        ),
    ]
