# Generated by Django 3.1.1 on 2021-01-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210124_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='8675c1eb-88fc-45a3-8494-1ff737ab0158', max_length=254),
        ),
    ]
