# Generated by Django 3.1.1 on 2021-01-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210125_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='a2f5c329-a415-4ad3-a6ab-7eb91c7f628e', max_length=254),
        ),
        migrations.AlterField(
            model_name='image_upload',
            name='user',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_desktop',
            field=models.ImageField(blank=True, max_length=1024, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_mobile',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url_desktop',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url_mobile',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='special',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
