# Generated by Django 3.1.1 on 2020-10-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_special_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='special',
            name='discounts',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
    ]
