# Generated by Django 3.1.1 on 2021-01-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210125_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='9e76839f-e5c6-4475-bad7-cf94efc1c8dc', max_length=254),
        ),
    ]
