# Generated by Django 3.1.1 on 2020-10-23 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='blog',
        ),
    ]
