# Generated by Django 3.1.1 on 2021-01-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210125_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='03530fd1-b27a-47ed-9213-4a0a25e59c7d', max_length=254),
        ),
    ]
