# Generated by Django 3.1.1 on 2021-01-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210125_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='6e016ff2-a327-47d1-8fdd-fc6d6a1c523d', max_length=254),
        ),
    ]
