# Generated by Django 3.1.1 on 2021-01-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210125_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='91ee91b5-14f3-472d-b8bf-9d7f6c88d963', max_length=254),
        ),
    ]
