# Generated by Django 3.1.1 on 2021-01-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210125_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='e2ee1827-b494-4c0a-8b3b-cb08a2b0eb03', max_length=254),
        ),
    ]
