# Generated by Django 3.1.1 on 2021-01-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210125_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='e3447417-21b5-421b-a967-df96d0ea6d3b', max_length=254),
        ),
    ]
