# Generated by Django 3.1.1 on 2020-11-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20201030_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digital_download',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
