# Generated by Django 3.1.1 on 2021-01-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210125_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='4353b6ff-2409-458a-a024-cf8e669639f1', max_length=254),
        ),
    ]
