# Generated by Django 3.1.1 on 2021-01-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210125_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='7976eda8-441d-41ce-a6e1-59317429c757', max_length=254),
        ),
        migrations.AlterField(
            model_name='special',
            name='discounts',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='name',
            field=models.CharField(blank=True, default='none', max_length=254, null=True),
        ),
    ]
