# Generated by Django 3.1.1 on 2020-11-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_digital_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='linked_to_blog',
            field=models.BooleanField(default=False),
        ),
    ]
