# Generated by Django 3.1.1 on 2021-01-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210125_2135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_upload',
        ),
    ]
