# Generated by Django 3.1.1 on 2020-11-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('time', models.CharField(default='Not downloaded yet', max_length=200)),
                ('downloaded', models.BooleanField(default=False)),
            ],
        ),
    ]
