# Generated by Django 3.1.1 on 2020-11-30 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_number_of_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default=uuid.UUID('99613e2c-5f76-4413-b7a9-725704bf33a6'), max_length=254),
        ),
    ]
