# Generated by Django 3.1.1 on 2020-12-04 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20201204_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='28d804ea-83fd-4d1c-814f-e847771b86fc', max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='special_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.special'),
        ),
    ]
