# Generated by Django 3.1.1 on 2020-12-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20201207_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='077632ae-eebf-4798-98b8-e564b7321072', max_length=254),
        ),
    ]
