# Generated by Django 3.1.1 on 2020-12-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20201209_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='d254d642-0eb6-496d-9560-d64c6d705b3a', max_length=254),
        ),
    ]
