# Generated by Django 3.1.1 on 2020-12-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20201209_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='5fbc2d89-3ae2-4c39-82dd-21349261ccbd', max_length=254),
        ),
    ]
