# Generated by Django 3.1.1 on 2020-12-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20201209_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='9bb7a1c2-9f65-4f30-9ec3-9f4b86b3e377', max_length=254),
        ),
    ]
