# Generated by Django 3.1.1 on 2020-12-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20201209_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='dab898fd-6c55-4b19-b936-18794a4e64ae', max_length=254),
        ),
    ]
