# Generated by Django 3.1.1 on 2021-01-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20201222_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='a6f2b9c7-fa96-4433-acba-dfeaac37c290', max_length=254),
        ),
    ]
