# Generated by Django 3.1.1 on 2021-01-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20210101_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='f145ea2c-1586-4e7c-85c0-25677cd4958a', max_length=254),
        ),
    ]
