# Generated by Django 3.1.1 on 2021-01-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_auto_20210101_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='caa41d5a-ce9a-4f4e-bd24-e8d9259ebc82', max_length=254),
        ),
    ]
