# Generated by Django 3.1.1 on 2021-01-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_auto_20210101_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='1e607a9d-e035-4734-b405-ac754538eeb2', max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='new_product', max_length=254),
        ),
    ]
