# Generated by Django 3.1.1 on 2021-01-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_auto_20210102_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='sku',
            field=models.CharField(default='72992dfd-8f65-4c7d-a7bf-3eb45da8b200', max_length=254),
        ),
    ]
